function a1(){
    localStorage.setItem("secondDream", false);
    localStorage.setItem("firstAwake", true);
}
function a2(){
    localStorage.setItem("thirdDream", false);
    localStorage.setItem("secondAwake",true);
    calculatingSecond();
}
function calculatingSecond(){
    var surfaced = localStorage.getItem("abridgeSurface");
    var explored = localStorage.getItem("exploreWater");
    var meal = localStorage.getItem("meal");
    if (surfaced=="true"){
        document.getElementById("starter").innerHTML += "The more you woke up, the more noticeable the soreness of your muscles was. If you didn't know any better, you would have thought you just spent a full day at the gym. Your breathing was ragged, and you had a strong inclination to dab at your forehead with your blanket. It was borderline gross when you touched the back of your hand to your forehead, and a bit embarrassing to boot.</br>"
        document.getElementById("starter").innerHTML += "</br>You were merely asleep, after all. Little work went into that...at least physically. Maybe instead of sleep walking you had been doing reps with your lamp."
    }
    else if (explored=="true"){
        document.getElementById("starter").innerHTML += "Anyone who says the fish or sharks are the most unsettling things about the deep ocean is very wrong. It's the silence and being left to your own thoughts. It was being alone to explore the depths and the hauntings left behind. You had gotten sufficient sleep. It would have to be sufficient.</br>"
    }
    else if (meal=="true"){
        document.getElementById("starter").innerHTML += "You finished up and put everything away neatly into containers that would be easy to pack for later. Looking at the clock, it was bizarre to see how much time had already passed. 3:45? Making waves. True to form, you had a smile on your face and a lightness in your step.</br>"
    }
}
function a3(){
    localStorage.setItem("fourthDream", false);
    localStorage.setItem("thirdAwake",true);
    calculatingThird()
}
function calculatingThird(){
    var exploreFire = localStorage.getItem("exploreFire")
    var outOfFire = localStorage.getItem("outOfFire")
    var music = localStorage.getItem("music")
    var tv = localStorage.getItem("tv")
    var meal = localStorage.getItem("meal")
    if (exploreFire=="true"){
        document.getElementById("starterInThree").innerHTML += "There was nothing like shattering like glass after being untouched by flames, only to be relieved to be chased by those flames, to make you question the genuine effectiveness of being asleep. You felt well-rested now, sure. And you...really didn't have room to complain about that, now that you thought about it. It's what you had wanted more than anything out of tonight. But it left you concerned enough to go check on each of the rooms of your place. You did not want to risk having to exit through a window because of an uncontrollable fire.</br>"
        document.getElementById("starterInThree").innerHTML += "</br>But that hadn't been the point of the dream. There was no smoke, nor was there fire to worry about. You should've known considering you weren't frightened by the fire. There had been something else that troubled you. Troubled you more than an entire area engulfed in flames- that was really something else.</br>"
        document.getElementById("starterInThree").innerHTML += "</br>It was probably better not to question the workings of your mind. It probably didn't mean anything aside from the pretty colors you got to see. Or maybe you were a bit cold and your subconscious was trying to compensate. No harm, no foul. Only a slight sense of wonder that you held for the origins, especially for the choice in scenery.</br>"
    }
    else if(outOfFire=="true"){
        document.getElementById("starterInThree").innerHTML += "Well. You couldn't say you were shaken, but you were decently shook. What in the name of all that is good was that? Were you a phoenix? Is that what you were meant to believe from that segment? Not that it wasn't cool.</br>"
        document.getElementById("starterInThree").innerHTML += "</br>But you had been fire. Actual, genuine fire. A source of heat and the ashes left behind. And then you weren't anymore. Just as you had hoped, you got out unscathed. Everything had been as you expected, and yet none of it at the same time. It was hard to say what you should or could make of it all.</br>"
        document.getElementById("starterInThree").innerHTML += "</br>And then there was the outside. How was it something you so readily accepted after everything else? It simply didn't make sense how calm you were in these dreams. You weren't even that collected about anything in real-life, how was it something you could dream about?</br>"
    }
    else if(music=="true"){
        document.getElementById("starterInThree").innerHTML += "As they say, all good things must come to an end. If you stayed on the music-high for too long, you wouldn't want to come back down. An escape couldn't become your reality, no matter how much you didn't want to return to what was on your mind before.</br>"
        document.getElementById("starterInThree").innerHTML += "</br>You shouldn't let the good vibes end so suddenly. For the time being, you'd let the unknown and uncertainty linger just as an afterthought. With a sigh, you tucked away the headphones and put your phone on the charger. You didn't want to risk it dying before you got the chance to come home.</br>"
    }
    else if (tv=="true"){
        document.getElementById("starterInThree").innerHTML += "You should've just watched one episode, apparently! Anything that wouldn't have left you on such a cliffhanger...you'd be thinking about it in your free time! Heck, you'd be thinking about it at other points too. This was just punishment for not going back to sleep before, wasn't it? If you had time for only one episode, you wouldn't be stuck in this limbo.</br>"
        document.getElementById("starterInThree").innerHTML += "</br>Something to look forward to for later, you supposed. You would just have to resist the temptation to look up what happens. It was a good thing you shouldn't have too much time with technology and just your own thoughts. If your job didn't require so much dedication and time, you would really be in trouble.</br>"
    }
    if(meal=="false"){
        document.getElementById("mealCheck").innerHTML += "</br>After your shower, you went to the kitchen to start putting together your lunch. You could probably grab something quick for breakfast on your way out."
    }
}
function second(){
    localStorage.setItem("secondDream", true);
    localStorage.setItem("firstAwake", false);
}

function third(){
    localStorage.setItem("thirdDream", true);
    localStorage.setItem("secondAwake",false);
}

function fourth(){
    localStorage.setItem("fourthDream", true);
    localStorage.setItem("thirdAwake",false);
}
function swimOut(){
    localStorage.setItem("abridgeSurface", true);
    localStorage.setItem("exploreWater", false);
}
function stayIn(){
    localStorage.setItem("exploreWater", true);
    localStorage.setItem("abridgeSurface", false);
}
function heat(){
    localStorage.setItem("exploreFire", true);
    localStorage.setItem("outOfFire", false);
}
function exitHeat(){
    localStorage.setItem("outOfFire", true);
    localStorage.setItem("exploreFire", false);
}
function family(){
    localStorage.setItem("family", true);
    localStorage.setItem("travel", false);
}
function travels(){
    localStorage.setItem("travel", true);
    localStorage.setItem("family", false);
}
function tv(){
    localStorage.setItem("tv", true);
    localStorage.setItem("meal", false);
}
function meal(){
    localStorage.setItem("meal", true);
    localStorage.setItem("tv", false);
}
function music(){
    localStorage.setItem("music", true);
    localStorage.setItem("puzzle", false);
}
function puzzle(){
    localStorage.setItem("puzzle", true);
    localStorage.setItem("music", false);
}
function calculatingBeforeWork(){
    //check if thirdDream is true for sufficient sleep
    var thirdDream = localStorage.getItem("thirdDream");
    var familia = localStorage.getItem("family");
    var traveling = localStorage.getItem("travel");
    var stayedHeat = localStorage.getItem("exploreFire");
    var exitedHeat = localStorage.getItem("outOfFire");
    var stayedWater = localStorage.getItem("exploreWater");
    var exitedWater = localStorage.getItem("abridgeSurface");
    if(thirdDream == "true"){
        localStorage.setItem("sufficientSleep",true)
        document.getElementById("driving").innerHTML += "Considering the amount of sleep you had gotten, you also grabbed your car keys from the counter nearby. It was weird to consider the last time you felt confident enough to drive was a few weeks ago. But here you were, feeling so well-rested. It was a necessary change in pace.</br>"
    }
    else{
        document.getElementById("driving").innerHTML += "Although you had successfully gotten a decent amount of sleep, you were still unsure if it would be enough to condone you driving on the roads. You had been up for hours now, but considering the oddity of your dreams and the possibility of falling asleep behind the wheel, you planned to take the bus instead. It was something you had gotten used to, anyway.</br>"
    }
    if(familia == "true"){
        localStorage.setItem("Fourth","1");
        document.getElementById("theCalm").innerHTML += "You were essentially a whirlpool of emotions. Your mind was set in visiting your family and your dog soon, fulfilling what you had gotten the opportunity to see just now. Tears pricked at your eyes, although none fell out, for the sheer lightness in what had started as dark. On a whole other train of thought- you had done it! You had slept through the night, albeit not very easily. The dreams had been a fair mix of confusing and wonderful. There had certainly been qualities to them that could've resulted in nightmarish visions. But in the end, that was never the case.</br>"
        document.getElementById("theCalm").innerHTML += "</br>Rolling out of bed, you hit the Snooze on the alarm clock for the time being. It would serve as a timer of sorts for everything else you still had to do. Showering, getting dressed, grabbing your materials for work...It was both a relief and a wake-up call to not have as much time as you typically did on the nights without sleep to get ready.</br>"
    }
    else if(traveling == "true"){
        localStorage.setItem("Fourth","2");
        document.getElementById("theCalm").innerHTML += "Wistful had to be the word to describe how you felt firsthand. Recently, you had fallen victim to letting others' perceptions of you drive your wishes. Or, at least, drive how loud they were. Had that twisted into troubles of having dreams and aspirations while you were trying to sleep, too? Had your subconscious disagreed so strongly with how you were being shaped, but still begrudgingly had to go along with it?</br>"
        document.getElementById("theCalm").innerHTML += "</br>You couldn't be sure if that was how it all worked. Regardless, you were content in this revelation. You would allow yourself to aim for heights, even if no one thought you would reach them. And if you stumble along the way, well, that was just life. Nothing was predictable, not everything could go exactly as you hoped, but it didn't mean that you should hope any less. Your new resolve made you smile.</br>"
        document.getElementById("theCalm").innerHTML += "</br>You'd have to give yourself more time to think on it later. It was time to get ready for work!</br"
    }
    if(stayedHeat == "true"){
        localStorage.setItem("Third","1");
    }
    else if(exitedHeat == "true"){
        localStorage.setItem("Third","2");
    }
    if(stayedWater == "true"){
        localStorage.setItem("Second","1");
    }
    else if (exitedWater=="true"){
        localStorage.setItem("Second","2");
    }
    
}
function calculatingWork(){
    var secondDream = localStorage.getItem("Second");
    var thirdDream = localStorage.getItem("Third");
    var fourthDream = localStorage.getItem("Fourth");
    var secondRand = Math.floor(Math.random()*2);
    var thirdRand =Math.floor(Math.random()*2);
    var fourthRand=Math.floor(Math.random()*2);
    document.getElementById("theStorm").innerHTML += "The office was pretty quiet when you arrived. Most people wouldn't be here for the next half hour, or so. You went to the floor your workstation was and put your lunch in the fridge with a note. It was time to enjoy your breakfast while you got your papers in order at a calm pace.</br>"
    document.getElementById("theStorm").innerHTML += "</br>While you were casually working, you couldn't help but notice the light flickering overhead. This tended to happen when the lights needed to be switched out, but your superstition led you to believe that it didn't happen to anyone else nearly as often as it happened to you. You never saw anyone else's light flickering! Although you didn't spend as much time under the other lights, you still saw them whenever you got up or were moving around. They needed to stop giving you the faulty lights.</br>"
    document.getElementById("theStorm").innerHTML += "</br>It was a somewhat amusing thought as you sorted your papers. Every so often you would stir the smoothie you held in your left hand, watching the bits of fruit that still remained swirl after the trail your straw left behind. There were more people starting to come in now, and so you would want to finish this up soon. You were close as it was already- so you got up from your seat and started working towards the sink.</br>"
    document.getElementById("theStorm").innerHTML += "</br>Anthony, one of the leading managers for your team, was right on your heels. A bit too literally. He must have been in a hurry for something important, considering that he didn't stop once. Not when his toes separated your shoe from your heel, not when you were stumbling as a result, and not even when your cup hit the floor. At least you didn't use anything breakable, though you still wish you had finished it off. There was a bit that had gotten onto the floor.</br>"
    document.getElementById("theStorm").innerHTML += "</br>Your luck wasn't completely out, though. There was someone who had heard the small commotion. Rileigh came to you with napkins in hand, giving you a few and picking up your cup for you. You whispered a thank you, smiling at them before picking up the small mess. It would've been worse if the carpet absorbed any more, or if there was something extra slippery and in the way about the spill. But it wasn't too much in the way, and it didn't take long. Rileigh coming in with the napkins really helped, and you could simply go back to your area to finish up your prep.</br>"
    if(secondDream =="1"){
        //ship
        document.getElementById("theStorm").innerHTML += "</br>When you were set in having the documentation pulled up for today's goals, you searched for your name. Peculiarly, you couldn't find it in its usual ordering. Assignments were typically given by last name, but yours simply wasn't there. Even when you used the handy dandy Ctrl+F, nothing popped up for your last or first name. It made you a bit nervous of the implications, but maybe because finishing touches were all that was left, not everyone had something to do? They should've contacted you if that had been the case, though. Surely you needed to be here for something.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You got up from your seat again and started towards Anthony's office. You knew he was here, and his office was nearby. The door was already open, which was easily preferred. You poked your head in and saw him at his desk. He had a book in hand, although you didn't think he could've been reading it. He was flipping through the pages at a rapid pace.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Excuse me?' You said calmly, gaining his attention with a slight jump. 'Sorry, I did not mean to startle you. I just came by to ask about the assignments for the day. I don't believe my name was listed?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Anthony sighed, returning his primary attention to the book. 'You would be correct. You just have to report all the files you worked on to me...' He paused briefly, as if a consideration was just striking. 'Actually, there is something I would like for you to do.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I still have to piece a lot of the project together. But today, one of our clients dropped this off.' He extended the book in offering for you to take. 'I can't for the life of me determine why or what part it has in the project, but they wanted there to be some ties with it. If you could go through and try to find some key words, maybe? That would be great.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You were at a bit of a loss for words. You hadn't expected to come into work today to read...but you went along with it. You accepted the book and noted the distinct feeling of leather in your hand. Without another word, you exited Anthony's office.</br>"
        document.getElementById("theStorm").innerHTML += "</br>A slight frown formed on your lips the more the book felt to weigh in your hand. There was something undeniably familiar about it. You were almost afraid to open it, for what if the pages were blank just as they had been in your dream?</br>"
        document.getElementById("theStorm").innerHTML += "</br>But that was ridiculous. That was a dream, this was reality- and the reality was you had an assignment on hand. You weren't about to get fired for not doing it at all.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Upon returning to your desk, you sat down and opened up the journal. Delicately written words filled the page. If it weren't for the dried ink and the crispness of the pages, you would've thought it to be a typed font rather than something handwritten. You started reading, instantaneously engulfed in the story that took to life on the pages. It was...remarkable. It seemed to be an autobiography, but even then, the nonfiction made easy work of drawing you in.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You were completely unaware of the amount of time that passed. If not for Rileigh looking in and tapping you on the shoulder, you probably would've missed your lunch break entirely. 'Whatcha reading there?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Not completely sure. But it's beautiful. Whoever wrote it does really well at painting scenes with words. I feel like I can see it all happening. It starts with someone who thought they were alone in their struggles, only to be helped at a point where they most needed it. I-'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'What did you do to it?' Rileigh had looked so invested in what you were saying, but upon looking at the book, their eyebrows furrowed. 'Was it something you were doing with disappearing ink, or something? Looking at it under a special light?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You furrowed your eyebrows in reply, glancing back at the book. Your eyes shot open...wide...when there were no longer words on the page.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You were rendered completely speechless. The same lost and confused sensation you held earlier this morning returned. It was a good thing you were still sitting because you definitely didn't think yourself steady enough to stand. 'I- I swear it was there. Words were there. I'm not just making it up.'"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh looked at you with genuinely concerned eyes. This was something you had hoped to avoid! You were getting sleep, they weren't supposed to be concerned about you anymore. But there was still so much going on that pointed to you not being okay. Why weren't you okay? What was all this? Was this actually just some bizarre dream? Some nightmare waiting to ramp up the difficulty level to expert? You certainly were not prepared enough for that.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You forced a smile and got up from the desk, shaking your head. 'I'll figure it out! Whatever it is. Don't think too much on it. I probably just had a momentary lapse in memory that perfectly explains the missing text.' You definitely did not. 'Oh! I actually got it now.' Who were you trying to convince, again? 'Let's go get some lunch. Eating will probably realign everything back in place.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh frowned for a moment, looking you up and down in attempts to find something to argue about. But, happily for you, they resolved to giving you a smile. 'If you say so. Let's do it, then.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Every so often while walking around with them, you pinched yourself to see if you would wake up. It was something you were highly hoping for at this point, considering this was starting to make less sense than any of your dreams ever had. But it was to no avail. You were still walking to retrieve your lunch with Rileigh. Everyone around you was laughing and conversing like it was any ordinary day. It may have been, for them.</br>"
    }
    else if(secondDream == "2"){
        //surface
        document.getElementById("theStorm").innerHTML += "</br>You ended right where you had began, at your station, shaking off the smoothie incident. It couldn't even be called an incident, it was so small. And today was going to be a day bigger than all of those small things, even put together! You got on to the shared documentation for today's assignments. Upon going to your name, you found a list of things to do. Without looking at the contents of the list, your heart dropped...but it ended up only being a list of where or to who you were meant to deliver the parts you had been working on. That would be a breeze! Electronically speaking, the files would be sent in seconds over email. The most difficult part there was making sure you had the right file attached. </br>"
        document.getElementById("theStorm").innerHTML += "</br>There were the cases that you had to navigate an in-person delivery for. Even that wouldn't be too bad. It was a good excuse to get some of your steps in. So! You got straight to work in dividing and conquering the emails. The easiest determination was sending them out separately so that each person involved only got one email with everything they needed, rather than groups of different emails. You knew what it was like to have a cluttered inbox, and you would not be the source of such chaos. In fact, there seemed to be a new stream of unreads that you had. If you were to guess based on what you could see, maybe half of them were relevant or important to the job. There would be at least a few spam and scam attempts, and utter nonsense made up the rest. </br>"
        document.getElementById("theStorm").innerHTML += "</br>As you were sending out your emails, you gradually grew more annoyed with the one at the top of your own inbox that was updating frequently. It looked like something under the 'nonsense' category. When you clicked it, there was a long thread of responses, none of the addresses one that you recognized. You decided you would look more into it after you had everything for your assigned tasks situated. The last thing you needed was for anyone to think you were choosing to not do your job. That was something in your control, unlike the sleep thing. You checked off the last email and retrieved the papers you had to go out and deliver next. </br>"
        document.getElementById("theStorm").innerHTML += "</br>There was a hurried quality to your steps, and though you didn't want to admit the cause, you knew it was the feeling that email thread gave you. Without looking at it, there was something off-putting. You could hope all you wanted to be proven incorrect when you had the chance to sit down and read it, but your gut told you that wasn't going to happen. You had to remind yourself to not look confused to each person you were handing off files to. If they asked what was on your mind, you didn't think you could do any justice in attempting to explain it. They would probably color you as crazy and maybe file a concerned report, if you were so unlucky.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Some of the people were on different floors since they were responsible for communications between groups, so you got even more of a workout than you thought. Beads of perspiration formed on your forehead, encouraging you to dab at them with your sleeve before they got to be too much. You were a bit out of breath, and your muscles were sore.</br>"
        document.getElementById("theStorm").innerHTML += "</br>...Just as they had been when you were swimming in the dream earlier. They felt like they were meeting some sort of resistance, working hard when you were hardly working at all. The longer you went for, the longer it took to find a breath. What, did that dream steal all of your oxygen?</br>"
        document.getElementById("theStorm").innerHTML += "</br>You huffed at yourself. It wasn't even a funny thought, though maybe that was because you were too afraid to laugh. What if you lost the breath you had and couldn't find it? It wasn't worth the risk, no matter how ridiculous of a thought it may be.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You pushed on, deciding that you would grab yourself some water on the way back to the desk. At least this was all the running you had today. When you were steps away from the final dropoff, you rushed harder. Faster. A desperation to get where you needed to go, and you needed to have the drive to get there. You got a strange glance when it was clear you had been running like you depended on it, but you just offered what you needed to pass as a reassuring smile. When the employee took the file in her hands, a deep breath filled you. As annoyed as you were that it waited so long to make up for it, you would thank it for appearing at all.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Before you could be there for what may be considered awkwardly long, you turned on your heel and went towards the exit. You returned to your seat and logged back into your laptop. It was time to get to the bottom of this. Which meant looking at the origins first.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Scrolling up...up...up...and up still, you were surprised when there was nowhere left to scroll. The bar along the side was so small, and getting smaller by the second. You were getting alerts to new replies, but you weren't interested in those right now. There was a video clip with the caption 'The Truth of What's Out There.' A scowl was the first reaction to come to mind, but something implored you to investigate further. If this was just some random troll, would it be getting so much attention from the respondents? And why would you be able to see all of their responses, for that matter?</br>"
        document.getElementById("theStorm").innerHTML += "</br>When you hit play, you braced for something dumb. Something fake. Something rehearsed. But it was a video of somewhere that you recognized. Somewhere down the street from where you were now. A car was being lifted off the street, but the only other thing to be seen was a person lifting and lowering their hand. Wherever they put it, the car would respond. There was a sound of sirens coming from far away. You paused the video to double-check if it was going on in real life, it wasn't. You pressed play again and it resumed with the car being set back down and the person running off. It left you feeling very odd. One of the first responses was someone asking about the 'impossible timestamp.' You looked at the footage and it was something meant to happen an hour from now.</br>"
        document.getElementById("theStorm").innerHTML += "</br>It had to be edited, right? There was no other explanation. That's what you would have to believe, because it was lunch, and Rileigh was already there to save you from yourself. 'Ready to eat?'"
        document.getElementById("theStorm").innerHTML += "</br>You nodded in affirmation, looking back at your screen to logout. And you found that the email was no longer there. You checked the trash, nothing was there either. You rapidly clicked to look wherever you could think to look, and there was nothing there.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'You don't sound ready.' Rileigh commented. 'What are you doing?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Something was there that isn't anymore.' You replied bluntly, inwardly wincing at the quiver in your voice.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh looked at you with genuinely concerned eyes. This was something you had hoped to avoid! You were getting sleep, they weren't supposed to be concerned about you anymore. But there was still so much going on that pointed to you not being okay. Why weren't you okay? What was all this? Was this actually just some bizarre dream? Some nightmare waiting to ramp up the difficulty level to expert? You certainly were not prepared enough for that.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You forced a smile and got up from the desk, shaking your head. 'I'll figure it out! Whatever it is. Don't think too much on it. I probably just had a momentary lapse in memory that perfectly explains the missing text.' You definitely did not. 'Oh! I actually got it now.' Who were you trying to convince, again? 'Let's go get some lunch. Eating will probably realign everything back in place.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh frowned for a moment, looking you up and down in attempts to find something to argue about. But, happily for you, they resolved to giving you a smile. 'If you say so. Let's do it, then.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Every so often while walking around with them, you pinched yourself to see if you would wake up. It was something you were highly hoping for at this point, considering this was starting to make less sense than any of your dreams ever had. But it was to no avail. You were still walking to retrieve your lunch with Rileigh. Everyone around you was laughing and conversing like it was any ordinary day. It may have been, for them.</br>"
    
    }
    else if(secondRand == 0){
        //ship
        document.getElementById("theStorm").innerHTML += "</br>When you were set in having the documentation pulled up for today's goals, you searched for your name. Peculiarly, you couldn't find it in its usual ordering. Assignments were typically given by last name, but yours simply wasn't there. Even when you used the handy dandy Ctrl+F, nothing popped up for your last or first name. It made you a bit nervous of the implications, but maybe because finishing touches were all that was left, not everyone had something to do? They should've contacted you if that had been the case, though. Surely you needed to be here for something.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You got up from your seat again and started towards Anthony's office. You knew he was here, and his office was nearby. The door was already open, which was easily preferred. You poked your head in and saw him at his desk. He had a book in hand, although you didn't think he could've been reading it. He was flipping through the pages at a rapid pace.</br>"
        document.getElementById("theStorm").innerHTML += '</br>"Excuse me?" You said calmly, gaining his attention with a slight jump. "Sorry, I did not mean to startle you. I just came by to ask about the assignments for the day. I do not believe my name was listed?"</br>'
        document.getElementById("theStorm").innerHTML += "</br>Anthony sighed, returning his primary attention to the book. 'You would be correct. You just have to report all the files you worked on to me...' He paused briefly, as if a consideration was just striking. 'Actually, there is something I would like for you to do.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I still have to piece a lot of the project together. But today, one of our clients dropped this off.' He extended the book in offering for you to take. 'I can't for the life of me determine why or what part it has in the project, but they wanted there to be some ties with it. If you could go through and try to find some key words, maybe? That would be great.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You were at a bit of a loss for words. You hadn't expected to come into work today to read...but you went along with it. You accepted the book and noted the distinct feeling of leather in your hand. Without another word, you exited Anthony's office.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Upon returning to your desk, you sat down and opened up the journal. Delicately written words filled the page. If it weren't for the dried ink and the crispness of the pages, you would've thought it to be a typed font rather than something handwritten. You started reading, instantaneously engulfed in the story that took to life on the pages. It was...remarkable. It seemed to be an autobiography, but even then, the nonfiction made easy work of drawing you in.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You were completely unaware of the amount of time that passed. If not for Rileigh looking in and tapping you on the shoulder, you probably would've missed your lunch break entirely. 'Whatcha reading there?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Not completely sure. But it's beautiful. Whoever wrote it does really well at painting scenes with words. I feel like I can see it all happening. It starts with someone who thought they were alone in their struggles, only to be helped at a point where they most needed it. I-'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'What did you do to it?' Rileigh had looked so invested in what you were saying, but upon looking at the book, their eyebrows furrowed. 'Was it something you were doing with disappearing ink, or something? Looking at it under a special light?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You furrowed your eyebrows in reply, glancing back at the book. Your eyes shot open...wide...when there were no longer words on the page.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh looked at you with genuinely concerned eyes. This was something you had hoped to avoid! You were getting sleep, they weren't supposed to be concerned about you anymore. But there was still so much going on that pointed to you not being okay. Why weren't you okay? What was all this? Was this actually just some bizarre dream? Some nightmare waiting to ramp up the difficulty level to expert? You certainly were not prepared enough for that.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You forced a smile and got up from the desk, shaking your head. 'I'll figure it out! Whatever it is. Don't think too much on it. I probably just had a momentary lapse in memory that perfectly explains the missing text.' You definitely did not. 'Oh! I actually got it now.' Who were you trying to convince, again? 'Let's go get some lunch. Eating will probably realign everything back in place.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh frowned for a moment, looking you up and down in attempts to find something to argue about. But, happily for you, they resolved to giving you a smile. 'If you say so. Let's do it, then.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Every so often while walking around with them, you pinched yourself to see if you would wake up. It was something you were highly hoping for at this point, considering this was starting to make less sense than any of your dreams ever had. But it was to no avail. You were still walking to retrieve your lunch with Rileigh. Everyone around you was laughing and conversing like it was any ordinary day. It may have been, for them.</br>"
    }
    else if(secondRand == 1){
        //surface
        document.getElementById("theStorm").innerHTML += "</br>You ended right where you had began, at your station, shaking off the smoothie incident. It couldn't even be called an incident, it was so small. And today was going to be a day bigger than all of those small things, even put together! You got on to the shared documentation for today's assignments. Upon going to your name, you found a list of things to do. Without looking at the contents of the list, your heart dropped...but it ended up only being a list of where or to who you were meant to deliver the parts you had been working on. That would be a breeze! Electronically speaking, the files would be sent in seconds over email. The most difficult part there was making sure you had the right file attached. </br>"
        document.getElementById("theStorm").innerHTML += "</br>There were the cases that you had to navigate an in-person delivery for. Even that wouldn't be too bad. It was a good excuse to get some of your steps in. So! You got straight to work in dividing and conquering the emails. The easiest determination was sending them out separately so that each person involved only got one email with everything they needed, rather than groups of different emails. You knew what it was like to have a cluttered inbox, and you would not be the source of such chaos. In fact, there seemed to be a new stream of unreads that you had. If you were to guess based on what you could see, maybe half of them were relevant or important to the job. There would be at least a few spam and scam attempts, and utter nonsense made up the rest. </br>"
        document.getElementById("theStorm").innerHTML += "</br>As you were sending out your emails, you gradually grew more annoyed with the one at the top of your own inbox that was updating frequently. It looked like something under the 'nonsense' category. When you clicked it, there was a long thread of responses, none of the addresses one that you recognized. You decided you would look more into it after you had everything for your assigned tasks situated. The last thing you needed was for anyone to think you were choosing to not do your job. That was something in your control, unlike the sleep thing. You checked off the last email and retrieved the papers you had to go out and deliver next. </br>"
        document.getElementById("theStorm").innerHTML += "</br>There was a hurried quality to your steps, and though you didn't want to admit the cause, you knew it was the feeling that email thread gave you. Without looking at it, there was something off-putting. You could hope all you wanted to be proven incorrect when you had the chance to sit down and read it, but your gut told you that wasn't going to happen. You had to remind yourself to not look confused to each person you were handing off files to. If they asked what was on your mind, you didn't think you could do any justice in attempting to explain it. They would probably color you as crazy and maybe file a concerned report, if you were so unlucky.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Some of the people were on different floors since they were responsible for communications between groups, so you got even more of a workout than you thought. Beads of perspiration formed on your forehead, encouraging you to dab at them with your sleeve before they got to be too much. You were a bit out of breath, and your muscles were sore.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You pushed on, deciding that you would grab yourself some water on the way back to the desk. At least this was all the running you had today. When you were steps away from the final dropoff, you rushed harder. Faster. A desperation to get where you needed to go, and you needed to have the drive to get there. You got a strange glance when it was clear you had been running like you depended on it, but you just offered what you needed to pass as a reassuring smile. When the employee took the file in her hands, a deep breath filled you. As annoyed as you were that it waited so long to make up for it, you would thank it for appearing at all.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Before you could be there for what may be considered awkwardly long, you turned on your heel and went towards the exit. You returned to your seat and logged back into your laptop. It was time to get to the bottom of this. Which meant looking at the origins first.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Scrolling up...up...up...and up still, you were surprised when there was nowhere left to scroll. The bar along the side was so small, and getting smaller by the second. You were getting alerts to new replies, but you weren't interested in those right now. There was a video clip with the caption 'The Truth of What's Out There.' A scowl was the first reaction to come to mind, but something implored you to investigate further. If this was just some random troll, would it be getting so much attention from the respondents? And why would you be able to see all of their responses, for that matter?</br>"
        document.getElementById("theStorm").innerHTML += "</br>When you hit play, you braced for something dumb. Something fake. Something rehearsed. But it was a video of somewhere that you recognized. Somewhere down the street from where you were now. A car was being lifted off the street, but the only other thing to be seen was a person lifting and lowering their hand. Wherever they put it, the car would respond. There was a sound of sirens coming from far away. You paused the video to double-check if it was going on in real life, it wasn't. You pressed play again and it resumed with the car being set back down and the person running off. It left you feeling very odd. One of the first responses was someone asking about the 'impossible timestamp.' You looked at the footage and it was something meant to happen an hour from now.</br>"
        document.getElementById("theStorm").innerHTML += "</br>It had to be edited, right? There was no other explanation. That's what you would have to believe, because it was lunch, and Rileigh was already there to save you from yourself. 'Ready to eat?'"
        document.getElementById("theStorm").innerHTML += "</br>You nodded in affirmation, looking back at your screen to logout. And you found that the email was no longer there. You checked the trash, nothing was there either. You rapidly clicked to look wherever you could think to look, and there was nothing there.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'You don't sound ready.' Rileigh commented. 'What are you doing?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Something was there that isn't anymore.' You replied bluntly, inwardly wincing at the quiver in your voice.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh looked at you with genuinely concerned eyes. This was something you had hoped to avoid! You were getting sleep, they weren't supposed to be concerned about you anymore. But there was still so much going on that pointed to you not being okay. Why weren't you okay? What was all this? Was this actually just some bizarre dream? Some nightmare waiting to ramp up the difficulty level to expert? You certainly were not prepared enough for that.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You forced a smile and got up from the desk, shaking your head. 'I'll figure it out! Whatever it is. Don't think too much on it. I probably just had a momentary lapse in memory that perfectly explains the missing text.' You definitely did not. 'Oh! I actually got it now.' Who were you trying to convince, again? 'Let's go get some lunch. Eating will probably realign everything back in place.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh frowned for a moment, looking you up and down in attempts to find something to argue about. But, happily for you, they resolved to giving you a smile. 'If you say so. Let's do it, then.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Every so often while walking around with them, you pinched yourself to see if you would wake up. It was something you were highly hoping for at this point, considering this was starting to make less sense than any of your dreams ever had. But it was to no avail. You were still walking to retrieve your lunch with Rileigh. Everyone around you was laughing and conversing like it was any ordinary day. It may have been, for them.</br>"
    
    }
    if(thirdDream =="1"){
        document.getElementById("theStorm").innerHTML += "</br>But it wasn't for you. Things were starting to be more than just coincidental deja vu. You needed to fully consider the possibility of a fire breaking out next, and what that would mean for you. Currently, you resided on the third floor of the building. There were windows all over the place. Even if there were none like the one you fell through in your dream, you were afraid of the implications. You didn't want there to be a raging fire, period. Depictions of wildfires that you saw every so often in headlines had you on-edge enough as it was. This was plain unnecessary.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You tried to relax and eat your worries away through the chocolate you packed. Attempting to listen to Rileigh and the others around you just proved to be like whitenoise. They were there, but they weren't enough to pull you out of your funk. If you were the only one that odd things were happening to, then no one would believe you if you tried to warn them. What exactly would you even say? If you said something so vague as something being off about the day, no one would be interested. Some smart guy would mention something about never having an on day, everyone else would laugh it off, and that would be the end of it.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Did that mean you should wait in silence? You expected something to happen. Wouldn't you rather look like a fool for a day and be wrong than keep things to yourself and be right? Did you want to be left alone to pick up such big pieces?</br>"
        document.getElementById("theStorm").innerHTML += "</br>...This wasn't at all what you had in mind for the day, but you knew you would rather be a fool. It didn't make admitting the possibility any easier, but you would get through it. You got through the sleepless nights, and now it was time to face the nightmarish day.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You stood up from your seat and cleared your throat, adding to the show by knocking on the counter. For good luck, perhaps. 'Excuse me, everyone? Sorry to...to interrupt.' Their eyes turning to you made you stammer. You could already feel the heat rising to your face, but you were committed.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'There's something strange going on here, today. I may be the only one capable of sensing it, and I know it sounds weird! But I promise I actually slept some last night. I actually think that may be one of the causes...' You bit your tongue to stop yourself from rambling.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I think the strange something is something bad. Very bad. And I think we should leave the office. We're all finished up with our materials for the project this week, right? Where'd the harm be?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Everyone stared at you blankly. You were sure some of them were thinking you would say 'Gotcha!' and cause a big laugh. Maybe a few were thinking of checking you in to be looked after. Anthony walked in amidst the now brazenly awkward silence, and within that moment, you felt like you were going to be sick.</br>"
        document.getElementById("theStorm").innerHTML += "</br>For when he walked in, goosebumps shot up your arms. The chills you had faced in your dream were undeniably present now. Right now. Regardless of what you wanted to do, you felt yourself retreating into the corner, Anthony looking at you with a raised eyebrow.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'What's going on in here, now? I thought I heard someone hoping everyone could get the rest of the day off?' The man started to laugh haughtily, the rest of the crowd erupting in belly laughs. The tension from before started to melt away, for everyone but you. 'My counter to that...Where's the harm in hanging around here for longer? You all find it pretty relaxing here, yeah?' His eyes shot to yours. 'You've nearly fallen asleep a few times.' More laughter. You just felt sicker.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Your knees and hands were shaking. You hoped the former wouldn't be as noticeable when you hid your hands behind your back. Anthony's eyes had yet to leave yours, and it was growing notably more unnerving. Something dangerous flashed in them, and you knew you had to find a way out. Even if it meant the dang window.</br>"
        document.getElementById("theStorm").innerHTML += "</br>A surprisingly convincing laugh escaped from your lips as well. You could tell it was unexpected because the manager looked off-guard. Good. 'You're right. Sorry, I have a really good show to get back to. I didn't bring any popcorn with me here.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I have some!' Rileigh popped up, bearing to you a heartbreakingly large grin. You wished for there to be a way to convince them to come with you, if no one else.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Awesome. Let's go get set up at my desk, then.' You grabbed Rileigh's arm and walked past your manager with a smile, although you didn't get very far before he grabbed onto your shoulder.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Chills ran their course down your spine, uneven and gnashing unseen teeth. You felt momentarily frozen in your place, and you were relieved when you found out you could still move your fingers.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I'm glad you came around.' Was all he said before letting go, moving further into the kitchen. You grit your teeth to stop yourself from saying anything that would give you away, continuing to guide Rileigh as far as you could get.</br>"
        document.getElementById("theStorm").innerHTML += "</br>When you were confident you were out of earshot, you pushed your friend into the nearest office and shut the door. It wasn't Anthony's, thank goodness. Rileigh looked at you bewildered. 'Wha-'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Please, Rileigh, you have to trust me.' You didn't leave them any space to question you. 'I know it's all looked and sounded crazy, but you need to know that I'm not. There's something up with Anthony, and all I want is for us to get out safe. I wanted to help the others too but...oh please, tell me you'll listen to me and believe me.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh's concerned look rebounded back onto their face from before as you pleaded with them. You were starting to feel hopeless and like you really wanted to sink into the floor...when the floor fell out from beneath you both. You looked up at what looked to be shattered glass above. When you looked back at Rileigh, who may as well have seen a ghost, they just nodded in silence.</br>"
        document.getElementById("theStorm").innerHTML += "</br>It was a good thing too, considering what you believed would soon be following you down. For more your sake than for Rileigh's, you latched onto them and did as you had just before. Wishing for more windows of opportunity to fall through, and to the first floor. Not bothering to pay any mind to the person in this office who was looking at you like you had four eyes (you may very well believe it at this point), you ushered yourself and Rileigh out of the Fire Window and darted towards the parking garage.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Please tell me you have your keys.' Rileigh was handing them to you halfway through your sentence. You unlocked the vehicle and got in, looking out the rearview window to see somethin you did not want to ever see. What had been a regular building before was now engulfed in colorful flames. Your colorful flames.</br>"
        //stayed in fire, escape through window
    }
    else if(thirdDream == "2"){
        //went out of fire through door
        document.getElementById("theStorm").innerHTML += "</br>But it was a day of disaster for you. You felt as if you were close to your boiling point. It had been fine when your dreams made little sense, there was no need for them to, but there was no explanation for what was happening now. Things didn't just vanish. And you were confident that you weren't losing whatever amount of marbles you had left. The next and only answer that you could look to was also one you wanted to avoid at all costs.</br>"
        document.getElementById("theStorm").innerHTML += "</br>It didn't really matter what you wanted. Instinctually, with how the logic was mapping out now, you knew that fire in some form was next on the list. Did that mean that it would happen here? That it would take place soon? And would there even be a way to escape through the door to a welcoming outside if there were flames trapping you in?</br>"
        document.getElementById("theStorm").innerHTML += "</br>There was more to it than just you, though. Whatever strangeness you were feeling, whatever the others weren't, it would still impact anyone here. The people that you had the pleasure of working with, even the more irritable ones that placed more weight onto your back. You didn't want them to be harmed just for being ignorant. Who knew- it may not even be their choice to be ignorant. Maybe you were just super sensitive to what was going to be taking place.</br>"
        document.getElementById("theStorm").innerHTML += "</br>However, that also entailed a challenge to you. There would be some level of convincing that you would have to attempt to accomplish. Who would listen to you, though? Your sleeping problems weren't a secret in the office, and your concerns may go in one ear and out the other. Just as a rumbling from above did...</br>"
        document.getElementById("theStorm").innerHTML += "</br>You released a sharp breath when you glanced up at the ceiling. You were expecting it to start falling in, or at least some dust to start sprinkling down. There was nothing. When Rileigh tapped on your arm, you leapt back as if they had burnt you. They looked hurt by your reaction, but you couldn't think much of it. You leaned forward and asked in a hushed whisper 'Did you hear that?'"
        document.getElementById("theStorm").innerHTML += "</br>'You mean people moving around furniture or something overhead? Yeah. Why? You look...really spooked, actually.' They looked they were about to reach out to you, but thought better of it. 'What's got you so worked up about it?'"
        document.getElementById("theStorm").innerHTML += "</br>'There's something wrong, Rileigh. You need to-' You paused when you felt a hand on your shoulder, noticing how hot your shoulder grew in revolt towards the touch. Luckily or unluckily, it seemed to go unnoticed by Anthony, who must've come in at some point while you were talking to Rileigh. 'Is there a problem here?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Before your friend could open their mouth, you shot them a quiet look that requested their silence. They seemed to get the message, but you would undoubtedly arise suspicions if you didn't fill the gap. 'Nothing's wrong.' You reassured cooly, honestly impressed by your untroubled tone. 'I just thought I heard signs of a storm. Was afraid of an electrical outage- but it wasn't thunder I heard. Just furniture.' You didn't dare break the eye contact you held so steadily. It would indirectly meant you had been swayed, and for some reason, you didn't want to give Anthony the slightest of hands. </br>"
        document.getElementById("theStorm").innerHTML += "</br>Your manager raised his eyebrow, squeezing your shoulder in what had to be mock reassurance. And you were afraid you were screwed because of it. You were flaming up again, and his hand lingered as if he had felt it. But it must have been a bad time, because he didn't do anything to act on it. 'That's good. You're in a safe place for a storm, anyway!'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Anthony walked off to talk with someone else, and you knew that you would have to move quickly if you had any hopes of getting out undetected. Or, at least, unscathed. You nonchalantly got up with Rileigh's wrist in hand, and started out to the door. Rileigh came along willingly, and you were grateful for it. You had no idea how dragging them would've went.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Are you going to tell me what's going on, or are we just going to walk in silence the rest of the way?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'You wouldn't be following me right now if I tried to tell you. You're just going to have to trust me on this one. Please? I just want us to get out of here safe.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Safe?' Rileigh questioned in shock. 'Why wouldn't we be safe here-' You gave them a pointed look that seemed to do its job. They grew quiet as you led them to the stairs and out the front door. </br>"
        document.getElementById("theStorm").innerHTML += "</br>'Do you have your keys?' Rileigh passed them off to you. Regardless of how you were feeling before, you were very aware now. Maybe even hyperaware. As soon as you opened the driver's door, you heard the whoosh of flames bursting to life. You looked back behind you to see a trail that caught fire from just inside the office doors. There was a peace to the outdoors that was all too familiar to you, but you would think about it later when you and Rileigh were safe. As soon as you were in and the two of you were buckled, you started to drive off.</br>"
    }
    else if(thirdRand == 0){
        //stayed in fire, escape through window
        document.getElementById("theStorm").innerHTML += "</br>You tried to relax and eat your worries away through the chocolate you packed. Attempting to listen to Rileigh and the others around you just proved to be like whitenoise. They were there, but they weren't enough to pull you out of your funk. If you were the only one that odd things were happening to, then no one would believe you if you tried to warn them. What exactly would you even say? If you said something so vague as something being off about the day, no one would be interested. Some smart guy would mention something about never having an on day, everyone else would laugh it off, and that would be the end of it.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Did that mean you should wait in silence? You expected something to happen. Wouldn't you rather look like a fool for a day and be wrong than keep things to yourself and be right? Did you want to be left alone to pick up such big pieces?</br>"
        document.getElementById("theStorm").innerHTML += "</br>...This wasn't at all what you had in mind for the day, but you knew you would rather be a fool. It didn't make admitting the possibility any easier, but you would get through it. You got through the sleepless nights, and now it was time to face the nightmarish day.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You stood up from your seat and cleared your throat, adding to the show by knocking on the counter. For good luck, perhaps. 'Excuse me, everyone? Sorry to...to interrupt.' Their eyes turning to you made you stammer. You could already feel the heat rising to your face, but you were committed.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'There's something strange going on here, today. I may be the only one capable of sensing it, and I know it sounds weird! But I promise I actually slept some last night. I actually think that may be one of the causes...' You bit your tongue to stop yourself from rambling.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I think the strange something is something bad. Very bad. And I think we should leave the office. We're all finished up with our materials for the project this week, right? Where'd the harm be?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Everyone stared at you blankly. You were sure some of them were thinking you would say 'Gotcha!' and cause a big laugh. Maybe a few were thinking of checking you in to be looked after. Anthony walked in amidst the now brazenly awkward silence, and within that moment, you felt like you were going to be sick.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'What's going on in here, now? I thought I heard someone hoping everyone could get the rest of the day off?' The man started to laugh haughtily, the rest of the crowd erupting in belly laughs. The tension from before started to melt away, for everyone but you. 'My counter to that...Where's the harm in hanging around here for longer? You all find it pretty relaxing here, yeah?' His eyes shot to yours. 'You've nearly fallen asleep a few times.' More laughter. You just felt sicker.</br>"
        document.getElementById("theStorm").innerHTML += "</br>A surprisingly convincing laugh escaped from your lips as well. You could tell it was unexpected because the manager looked off-guard. Good. 'You're right. Sorry, I have a really good show to get back to. I didn't bring any popcorn with me here.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I have some!' Rileigh popped up, bearing to you a heartbreakingly large grin. You wished for there to be a way to convince them to come with you, if no one else.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Awesome. Let's go get set up at my desk, then.' You grabbed Rileigh's arm and walked past your manager with a smile, although you didn't get very far before he grabbed onto your shoulder.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Chills ran their course down your spine, uneven and gnashing unseen teeth. You felt momentarily frozen in your place, and you were relieved when you found out you could still move your fingers.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I'm glad you came around.' Was all he said before letting go, moving further into the kitchen. You grit your teeth to stop yourself from saying anything that would give you away, continuing to guide Rileigh as far as you could get.</br>"
        document.getElementById("theStorm").innerHTML += "</br>When you were confident you were out of earshot, you pushed your friend into the nearest office and shut the door. It wasn't Anthony's, thank goodness. Rileigh looked at you bewildered. 'Wha-'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Please, Rileigh, you have to trust me.' You didn't leave them any space to question you. 'I know it's all looked and sounded crazy, but you need to know that I'm not. There's something up with Anthony, and all I want is for us to get out safe. I wanted to help the others too but...oh please, tell me you'll listen to me and believe me.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh's concerned look rebounded back onto their face from before as you pleaded with them. You were starting to feel hopeless and like you really wanted to sink into the floor...when the floor fell out from beneath you both. You looked up at what looked to be shattered glass above. When you looked back at Rileigh, who may as well have seen a ghost, they just nodded in silence.</br>"
        document.getElementById("theStorm").innerHTML += "</br>For more your sake than for Rileigh's, you latched onto them and did as you had just before. Wishing for more windows of opportunity to fall through, and to the first floor. Not bothering to pay any mind to the person in this office who was looking at you like you had four eyes (you may very well believe it at this point), you ushered yourself and Rileigh out of the Fire Window and darted towards the parking garage.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Please tell me you have your keys.' Rileigh was handing them to you halfway through your sentence. You unlocked the vehicle and got in, looking out the rearview window to see somethin you did not want to ever see. What had been a regular building before was now engulfed in colorful flames.</br>"
    }
    else if(thirdRand == 1){
        //went out of fire through door
        document.getElementById("theStorm").innerHTML += "</br>But it was a day of disaster for you. You felt as if you were close to your boiling point. It had been fine when your dreams made little sense, there was no need for them to, but there was no explanation for what was happening now. Things didn't just vanish. And you were confident that you weren't losing whatever amount of marbles you had left.</br>"
        document.getElementById("theStorm").innerHTML += "</br>There was more to it than just you, though. Whatever strangeness you were feeling, whatever the others weren't, it would still impact anyone here. The people that you had the pleasure of working with, even the more irritable ones that placed more weight onto your back. You didn't want them to be harmed just for being ignorant. Who knew- it may not even be their choice to be ignorant. Maybe you were just super sensitive to what was going to be taking place.</br>"
        document.getElementById("theStorm").innerHTML += "</br>However, that also entailed a challenge to you. There would be some level of convincing that you would have to attempt to accomplish. Who would listen to you, though? Your sleeping problems weren't a secret in the office, and your concerns may go in one ear and out the other. Just as a rumbling from above did...</br>"
        document.getElementById("theStorm").innerHTML += "There was nothing weird yet that you could see as you looked above you. When Rileigh tapped on your arm, you leapt back as if they had burnt you. They looked hurt by your reaction, but you couldn't think much of it. You leaned forward and asked in a hushed whisper 'Did you hear that?</br>'"
        document.getElementById("theStorm").innerHTML += "</br>'You mean people moving around furniture or something overhead? Yeah. Why? You look...really spooked, actually.' They looked they were about to reach out to you, but thought better of it. 'What's got you so worked up about it?'"
        document.getElementById("theStorm").innerHTML += "</br>'There's something wrong, Rileigh. You need to-' You paused when you felt a hand on your shoulder, noticing how hot your shoulder grew in revolt towards the touch. Luckily or unluckily, it seemed to go unnoticed by Anthony, who must've come in at some point while you were talking to Rileigh. 'Is there a problem here?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Before your friend could open their mouth, you shot them a quiet look that requested their silence. They seemed to get the message, but you would undoubtedly arise suspicions if you didn't fill the gap. 'Nothing's wrong.' You reassured cooly, honestly impressed by your untroubled tone. 'I just thought I heard signs of a storm. Was afraid of an electrical outage- but it wasn't thunder I heard. Just furniture.' You didn't dare break the eye contact you held so steadily. It would indirectly meant you had been swayed, and for some reason, you didn't want to give Anthony the slightest of hands. </br>"
        document.getElementById("theStorm").innerHTML += "</br>Your manager raised his eyebrow, squeezing your shoulder in what had to be mock reassurance. You couldn't help but freeze up for a moment, for as you felt feverish again, his hand lingered as if he had felt it. But it must have been a bad time, because he didn't do anything to act on it. 'That's good. You're in a safe place for a storm, anyway!'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Anthony walked off to talk with someone else, and you knew that you would have to move quickly if you had any hopes of getting out undetected. Or, at least, unscathed. You nonchalantly got up with Rileigh's wrist in hand, and started out to the door. Rileigh came along willingly, and you were grateful for it. You had no idea how dragging them would've went.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Are you going to tell me what's going on, or are we just going to walk in silence the rest of the way?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'You wouldn't be following me right now if I tried to tell you. You're just going to have to trust me on this one. Please? I just want us to get out of here safe.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Safe?' Rileigh questioned in shock. 'Why wouldn't we be safe here-' You gave them a pointed look that seemed to do its job. They grew quiet as you led them to the stairs and out the front door. </br>"
        document.getElementById("theStorm").innerHTML += "</br>'Do you have your keys?' Rileigh passed them off to you. Regardless of how you were feeling before, you were very aware now. Maybe even hyperaware. As soon as you opened the driver's door, you heard the whoosh of flames bursting to life. You looked back behind you to see a trail that caught fire from just inside the office doors. There was a peace to the outdoors that was just as unsettling as it was encouraging, but you would think about it later when you and Rileigh were safe. As soon as you were in and the two of you were buckled, you started to drive off.</br>"
    }
    if(fourthDream =="1") {
        //family memories, moving forward
        document.getElementById("theStorm").innerHTML += "</br>It was okay to not know, but you couldn't let it destroy you. It was evident that you didn't know what was going on. It must've been, because Rileigh hadn't said a word to you for the last thirty minutes. Whoever was on the radio now must have known a whole lot more. They sounded like a news reporter who was on the scene. As if your office building going up in flames wasn't terrifying enough, there was so much more going on that you could only comprehend because you managed to sort of see it coming.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Other places were freezing over. Cars were being lifted and thrown every which way, people too. Mostly everyone involved was so scared and confused, but there were a handful of those that sounded like they knew what was going on. Maybe they were just making it up as they went. You had a strong feeling that Anthony knew. That he was planning something to go down if it wasn't for the flames. </br>"
        document.getElementById("theStorm").innerHTML += "</br>Although you didn't want to admit it, the odds of those flames stemming from you were too high to ignore. You found comfort in them. You could only hope that the others in the building could as well. From the sounds of it, everyone had gotten out of there. Was it wrong you weren't relieved that likely meant Anthony too?</br>"
        document.getElementById("theStorm").innerHTML += "</br>You felt like there was no time for you to be confused. Undoubtedly, you were being sought after now. You didn't know if there was a right or wrong option about where to go. If you went to your place, would he be waiting there? If you went to visit your parents, would they be terrified of your capabilities? Did they already know about them? If they did, why wouldn't they have said anything? Would Anthony just follow you there, too?</br>"
        document.getElementById("theStorm").innerHTML += "</br>But you had went home in your dream, hadn't you? Or at least, you were placed there. If you ignored that, would the consequences be worse than if you followed? You drummed your fingers anxiously on the steering wheel, not noticing that Rileigh had turned the radio off until they poked your arm.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'You're thinking.' They started bluntly. 'And whatever you're thinking...you should trust it.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Opening your mouth to make a rebuttal, you were just as quickly quieted by their continuation. 'I don't know where I'd be if you didn't get me to come out with you. You knew it before it was happening. Whatever you're thinking, you need to do it.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You bit your lip as you went back to thinking. You were afraid that this was the time you were actually wrong.</br>"
        document.getElementById("theStorm").innerHTML += "</br>What did that mean, really? That you were just going to keep driving aimlessly and hope for an alternative to pop up? You were going to dedicate time to trying to force another answer, instead of finding one of your own? You couldn't do that. Especially not now. Today was the day that you counted on yourself, and that couldn't stop just because you were scared. You started on the way down a familiar path.</br>"
        document.getElementById("theStorm").innerHTML += "</br>By the time you reached your house, it was dark outside. The street lamps were on, and there was a chill when you stepped outside the vehicle. The driveway of your childhood home was already full, and there were a number of people outside. Instantly you were met by the soothing embrace of your mother.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I think there's something wrong with me.' You mumbled into her shoulder, only to be shushed by the notion.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'There's nothing wrong with you. I promise. We hadn't told you before because we didn't think there was anything to tell. You never showed any of the signs when you were little...'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You felt the small whack of a dog's tail against your leg, immediately calling you down to the ground to get a dog hug, one of the best things in existence. You wanted to cry for so many reasons, and yet no tears would form. Your dad came over with one of the other people that were huddled around each other before. Someone that looked...familiar."
        document.getElementById("theStorm").innerHTML += "</br>'Apologies for interrupting.' The newcomer said, her voice unmistakable. She was Evalyn- the one from the new and supernatural crime show you had been watching. 'I'm Evalyn, and I think I can help explain. How about we all go inside? I promise, we'll all be safe in there. I have friends that can guarantee it.'</br>"
    }
    else if(fourthDream == "2"){
        //travelling but a dream
        document.getElementById("theStorm").innerHTML += "</br>Why let them take the reigns of your dreams and turn them into nightmarish folly? That was in some regard what was going on here, wasn't it? As weird as your dreams may have been, you were calm in each of them. You were not concerned or worried or frightened. In real life, in the present, you were all three of those on overdrive. It probably wasn't the best energy for Rileigh to be in the company of, but they had been quiet since you started travelling thirty minutes ago. Of course, you really couldn't blame them. You wouldn't know what to say to you right now either.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You had yet to decide where the end destination was. Could there even be one? Was there a place where you could go that would be safe for everyone involved? Or was this it...the chance to travel to new places to at least temporarily escape the troubles of here? Would it be that simple? Was this happening in the other places of the world?</br>"
        document.getElementById("theStorm").innerHTML += "</br>With so much going on inside your head, you were glad that you were still on the road. And that you weren't flying or falling or facing blazing and freezing temperatures in one big conglomeration. When you heard your ringtone, though, you were surprised that you didn't set fire to something else. You were about 95% sure that was all you, earlier.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh picked it up and answered it for you, putting it on speaker. You heard both of your parents on the other end immediately, delving into details that you could barely catch with all things considered.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Psychic...mother was one...no signs as a child...powers...has there been a lot on your mind lately...have you noticed anything different...there was a spike in something today, usually things are pretty stagnant...' Together they formed cohesive thoughts, but there was nothing cohesive about the rate at which things were being processed in your head.</br>"
        document.getElementById("theStorm").innerHTML += "</br>When they were finally done and were met with your silence, they were making sure you were still there. Rileigh had your back. 'Hi. Yeah, sorry, currently driving. Don't really know...where to-'"
        document.getElementById("theStorm").innerHTML += "</br>'OH! You're driving? That's actually perfect.' Your mother sounded much too bubbly, but you were intrigued by it nonetheless. 'Honey, go to the airport. There's a friend just coming in that can take you back with them. You always wanted to get out of here, right? They can help you with everything. We can even meet you there, as well. And we'll talk about everything.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You didn't talk again for a few moments. And then, '...You'll be there too?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'As long as you want us there-'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Absolutely.' A softer, weaker 'Please...' followed, and you could imagine them starting to pack immediately after. For all you knew, it was another vision.</br>"
    }
    else if(fourthRand == 0){
        //family memories, moving forward
        document.getElementById("theStorm").innerHTML += "</br>It was okay to not know, but you couldn't let it destroy you. It was evident that you didn't know what was going on. It must've been, because Rileigh hadn't said a word to you for the last thirty minutes. Whoever was on the radio now must have known a whole lot more. They sounded like a news reporter who was on the scene.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Other places were freezing over. Cars were being lifted and thrown every which way, people too. Mostly everyone involved was so scared and confused, but there were a handful of those that sounded like they knew what was going on. Maybe they were just making it up as they went. You had a strong feeling that Anthony knew. That he was planning something to go down if it wasn't for the flames. </br>"
        document.getElementById("theStorm").innerHTML += "</br>Although you didn't want to admit it, the odds of those flames stemming from you were too high to ignore. You found comfort in them. You could only hope that the others in the building could as well. From the sounds of it, everyone had gotten out of there. Was it wrong you weren't relieved that likely meant Anthony too?</br>"
        document.getElementById("theStorm").innerHTML += "</br>You felt like there was no time for you to be confused. Undoubtedly, you were being sought after now. You didn't know if there was a right or wrong option about where to go. If you went to your place, would he be waiting there? If you went to visit your parents, would they be terrified of your capabilities? Did they already know about them? If they did, why wouldn't they have said anything? Would Anthony just follow you there, too?</br>"
        document.getElementById("theStorm").innerHTML += "</br>'You're thinking.' Rileigh started bluntly, calling you from out of your mind. 'And whatever you're thinking...you should trust it.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>Opening your mouth to make a rebuttal, you were just as quickly quieted by their continuation. 'I don't know where I'd be if you didn't get me to come out with you. You knew something was wrong when no one else did. Whatever you're thinking, you need to do it.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You bit your lip as you went back to thinking. You were afraid that this was the time you were actually wrong.</br>"
        document.getElementById("theStorm").innerHTML += "</br>What did that mean, really? That you were just going to keep driving aimlessly and hope for an alternative to pop up? You were going to dedicate time to trying to force another answer, instead of finding one of your own? You couldn't do that. Especially not now. Today was the day that you counted on yourself, and that couldn't stop just because you were scared. You started on the way down a familiar path.</br>"
        document.getElementById("theStorm").innerHTML += "</br>By the time you reached your house, it was dark outside. The street lamps were on, and there was a chill when you stepped outside the vehicle. The driveway of your childhood home was already full, and there were a number of people outside. Instantly you were met by the soothing embrace of your mother.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'I think there's something wrong with me.' You mumbled into her shoulder, only to be shushed by the notion.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'There's nothing wrong with you. I promise. We hadn't told you before because we didn't think there was anything to tell. You never showed any of the signs when you were little...'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You felt the small whack of a dog's tail against your leg, immediately calling you down to the ground to get a dog hug, one of the best things in existence. You wanted to cry for so many reasons, and yet no tears would form. Your dad came over with one of the other people that were huddled around each other before. Someone that looked...familiar."
        document.getElementById("theStorm").innerHTML += "</br>'Apologies for interrupting.' The newcomer said, her voice unmistakable. She was Evalyn- the one from the new and supernatural crime show you had been watching. 'I'm Evalyn, and I think I can help explain. How about we all go inside? I promise, we'll all be safe in there. I have friends that can guarantee it.'</br>"
    }
    else if(fourthRand == 1){
        //travelling but a dream
        document.getElementById("theStorm").innerHTML += "</br>In real life, in the present, you were concerned, worried, and frightened on overdrive. It probably wasn't the best energy for Rileigh to be in the company of, but they had been quiet since you started travelling thirty minutes ago. Of course, you really couldn't blame them. You wouldn't know what to say to you right now either.</br>"
        document.getElementById("theStorm").innerHTML += "</br>You had yet to decide where the end destination was. Could there even be one? Was there a place where you could go that would be safe for everyone involved? Or was this it...the chance to travel to new places to at least temporarily escape the troubles of here? Would it be that simple? Was this happening in the other places of the world?</br>"
        document.getElementById("theStorm").innerHTML += "</br>With so much going on inside your head, you were glad that you were still on the road. And that you weren't flying or falling or facing blazing and freezing temperatures in one big conglomeration. When you heard your ringtone, though, you were surprised that you didn't set fire to something else. You were about 95% sure that was all you, earlier.</br>"
        document.getElementById("theStorm").innerHTML += "</br>Rileigh picked it up and answered it for you, putting it on speaker. You heard both of your parents on the other end immediately, delving into details that you could barely catch with all things considered.</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Psychic...mother was one...no signs as a child...powers...has there been a lot on your mind lately...have you noticed anything different...there was a spike in something today, usually things are pretty stagnant...' Together they formed cohesive thoughts, but there was nothing cohesive about the rate at which things were being processed in your head.</br>"
        document.getElementById("theStorm").innerHTML += "</br>When they were finally done and were met with your silence, they were making sure you were still there. Rileigh had your back. 'Hi. Yeah, sorry, currently driving. Don't really know...where to-'"
        document.getElementById("theStorm").innerHTML += "</br>'OH! You're driving? That's actually perfect.' Your mother sounded much too bubbly, but you were intrigued by it nonetheless. 'Honey, go to the airport. There's a friend just coming in that can take you back with them. You always wanted to get out of here, right? They can help you with everything. We can even meet you there, as well. And we'll talk about everything.'</br>"
        document.getElementById("theStorm").innerHTML += "</br>You didn't talk again for a few moments. And then, '...You'll be there too?'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'As long as you want us there-'</br>"
        document.getElementById("theStorm").innerHTML += "</br>'Absolutely.' A softer, weaker 'Please...' followed, and you could imagine them starting to pack immediately after.</br>"
    }
}
function achievements(){
    var fourthDream = localStorage.getItem("fourthDream");
    var mealTime = localStorage.getItem("meal");
    var musical = localStorage.getItem("music");
    var puzzler = localStorage.getItem("puzzle");
    var tvTime = localStorage.getItem("tv");
    var img = document.createElement("img");
    if(fourthDream=="true"||localStorage.getItem("overallFourth")=="true"){
        img.src = "CompleteDreamer.png"
        img.alt = "You slept through the night to get this token"
        var src = document.getElementById("images")
        src.appendChild(img)
        localStorage.setItem("overallFourth", true)
    }
    if(mealTime=="true"||localStorage.getItem("overallMeal")=="true"){
        img = document.createElement("img");
        img.src = "BonusMeal.png"
        img.alt = "You prepared special meals for yourself ahead of time to complete this token."
        var src = document.getElementById("images")
        src.appendChild(img)
        localStorage.setItem("overallMeal",true)
    }
    if(musical=="true"||localStorage.getItem("overallMusic")=="true"){
        img = document.createElement("img");
        img.src = "MusicLover.png"
        img.alt = "You jammed out to music to earn this token."
        var src = document.getElementById("images")
        src.appendChild(img)
        localStorage.setItem("overallMusic",true)
    }
    if(puzzler=="true"||localStorage.getItem("overallPuzzle")=="true"){
        img = document.createElement("img");
        img.src = "PuzzleMaker.png"
        img.alt = "You worked on becoming a puzzle master to earn this token."
        var src = document.getElementById("images")
        src.appendChild(img)
        localStorage.setItem("overallPuzzle",true)
    }
    if(tvTime=="true"||localStorage.getItem("overallEv")=="true"){
        img = document.createElement("img");
        img.src = "TheOriginsofEvalyn.png"
        img.alt = "You aquired Evalyn lore to get this token."
        var src = document.getElementById("images")
        src.appendChild(img)
        localStorage.setItem("overallEv",true)
        localStorage.setItem("tv", false);
    }
    localStorage.setItem("secondDream", false);
    localStorage.setItem("firstAwake", false);
    localStorage.setItem("thirdDream", false);
    localStorage.setItem("secondAwake",false);
    localStorage.setItem("fourthDream", false);
    localStorage.setItem("thirdAwake",false);
    localStorage.setItem("abridgeSurface", false);
    localStorage.setItem("exploreWater", false);
    localStorage.setItem("exploreFire", false);
    localStorage.setItem("outOfFire", false);
    localStorage.setItem("family", false);
    localStorage.setItem("travel", false);
    localStorage.setItem("meal", false);
    localStorage.setItem("music", false);
    localStorage.setItem("puzzle", false);
}